import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import { Toaster } from 'react-hot-toast';
import Footer from "@/components/layout/Footer";
import "bootstrap/dist/css/bootstrap.min.css";
import LoaderWrapper from "@/components/home/LoaderWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anubhav",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        <Toaster position="top-right"/>
        <LoaderWrapper>
          {children}
        </LoaderWrapper>
        <Footer/>
      </body>
    </html>
  );
}
